name: Deploy Project
on: [push, repository_dispatch]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --prod --pure-lockfile
      - name: Build
        run: yarn run build
        env:
          NODE_ENV: production
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          ACCESS_TOKEN: ${{secrets.GH_PAT}}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: public
